Ensure error during rehash doesn't fail the hook
To ensure the npm install/uninstall command itself isn't rolled back, be
absolutely sure that the hook script exits cleanly. If the rehash fails,
report it but exit 0.

diff --git a/libexec/nodenv-rehash b/libexec/nodenv-rehash
--- a/libexec/nodenv-rehash
+++ b/libexec/nodenv-rehash
@@ -4,7 +4,7 @@
 : "${npm_package_name:=}"
 
 warn() {
-  echo "${1:-$(cat -)}" >&2
+  echo "${1-$(cat -)}" >&2
 }
 
 error() {
@@ -28,4 +28,5 @@ if ! main_package; then
   exit
 fi
 
-nodenv rehash
+nodenv rehash || error "error rehashing; manual \`nodenv rehash' likely needed"
+exit 0
