Ensure required vars don't cause a failure exit
Exiting with a failure could cause npm to rollback the
install/uninstall and we don't want that.

Instead of erroring on missing vars, just emit a warning message.
Additionally, instead of defaulting to doing nothing in this error case,
we may as well still rehash. We could be doing more work than is
necessary, but it is an error case at that point after all. May as well
be maximally useful about it.

diff --git a/libexec/nodenv-rehash b/libexec/nodenv-rehash
--- a/libexec/nodenv-rehash
+++ b/libexec/nodenv-rehash
@@ -1,9 +1,24 @@
 #!/usr/bin/env bash
 
-main_package() {
-  local current_package='\["'${npm_package_name:?}'("\]|@)'
+: "${npm_config_argv:=}"
+: "${npm_package_name:=}"
 
-  [[ ${npm_config_argv:?} =~ $current_package ]]
+warn() {
+  echo "${1:-$(cat -)}" >&2
+}
+
+error() {
+  warn "nodenv-package-rehash: $1"
+}
+
+main_package() {
+  if [ -z "$npm_package_name" ] || [ -z "$npm_config_argv" ]; then
+    error "can't determine target package"
+    return 0 # still rehash by default
+  fi
+
+  local current_package='\["'$npm_package_name'("\]|@)'
+  [[ $npm_config_argv =~ $current_package ]]
 }
 
 # This hook gets invoked when installing dependencies, too, but
